import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";
import QueryProvider from "./queries/QueryProvider";
import Header from "./contact/components/Header";

export const metadata: Metadata = {
  title: {
    default: "مدیریت مخاطبین",
    template: "مدیریت مخاطبین | %s",
  },
  description: "Generated by Morteza",
};

const vazirmatn: NextFontWithVariable = localFont({
  src: "../../public/assets/fonts/Vazirmatn.woff2",
  display: "swap",
  variable: "--font-vazirmatn",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa-IR"
      dir="rtl"
      className={`${vazirmatn.variable} font-vazirmatn`}
    >
      <body>
        <QueryProvider>
          <div>
            <Header />
            <div className="flex">
              
              {children}
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
