import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { NextFont } from "next/dist/compiled/@next/font";

export const metadata: Metadata = {
  title: "مدیریت مخاطبین",
  description: "Generated by Morteza",
};

const vazir: NextFont = localFont({
  src: "./Vazir.woff2",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" className={vazir.className}>
      <body>{children}</body>
    </html>
  );
}
