import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";

export const metadata: Metadata = {
  title: "مدیریت مخاطبین",
  description: "Generated by Morteza",
};

const vazirmatn : NextFontWithVariable = localFont({
  src: "../assets/fonts/Vazirmatn.woff2",
  display: "swap",
  variable: '--font-vazirmatn',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" className={`${vazirmatn.variable} font-vazirmatn`}>
      <body>{children}</body>
    </html>
  );
}
